name: nestery_flutter
description: Nestery mobile application for hotel booking and management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State management
  flutter_riverpod: ^2.4.9
  provider: ^6.1.5
  # Navigation
  go_router: ^15.1.2
  # Network and API
  dio: ^5.4.0
  http: ^1.1.2
  dio_cache_interceptor: ^4.0.3
  # Replaced sembast store with drift store for caching
  http_cache_drift_store: ^7.0.0
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.33 # For native SQLite bindings, updated to match drift_dev
  # Storage and persistence
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  # File Picker
  file_picker: ^10.1.9
  # Environment configuration
  flutter_dotenv: ^5.1.0
  # UI components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  # Maps and location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  # Date and time
  intl: ^0.19.0
  # Analytics and monitoring
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  # Social sharing
  share_plus: ^7.2.1
  # Payments
  flutter_stripe: ^9.6.0 # Updated to match lock file
  # Animations
  lottie: ^2.7.0
  # QR Code and Image Picker
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  # Utilities
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  path: ^1.9.0 # For path manipulation with Drift/sqflite
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1
  google_mobile_ads: ^6.0.0 # Added Google AdMob
  uuid: ^4.2.2
  flutter_native_splash: ^2.4.4 # Updated to match lock file
  # Charting
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^24.1.43
  # Code generation (needed at runtime)
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4 # Updated as per task
  build_runner: ^2.4.7
  drift_dev: ^2.15.0 # For Drift code generation
  freezed: ^2.4.7 # For freezed models (dev only)
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#1E88E5"
  image: assets/images/splash_logo.png
  android: true
  ios: true
