export enum PartnerCategoryEnum {
  TOUR_OPERATOR = 'TOUR_OPERATOR',
  ACTIVITY_PROVIDER = 'ACTIVITY_PROVIDER',
  RESTAURANT = 'RESTAURANT',
  TRANSPORTATION = 'TRANSPORTATION',
  ECOMMERCE = 'ECOMMERCE',
}
